### ISSUE TITLE
Error of treetagger due to missing punctuation

### ISSUE THREAD

**Issue by morethanbooks** [cligs/tmw#10]
I checked the texts and I saw that the punctuation marks are deleted very early in the process. I wondered if the treetagger wouldn't have problems with that after that. And it does in deed. Every thing with its first letter in capital is analysed as an noun, although is very cleared that is something else. In Spanish for example:
Habréis    NP  <unknown>
Por NC  <unknown>
Admiremos   NP  <unknown>
Con NP  <unknown>

The tmw script deletes this characters in the function segmenter. I understand that this characters are not important for the topic modelling, but we can leave them in the first steps of the process, because after the lemmatisation they are going to be deleted anyway.

Besides, the segmenter deletes only some punctuation marks, not all of them. Punctuation marks that are missing:
: ( )  ¿ !

**Comment by christofs** [comment]
Thank you for pointing this out! I suggest the following solution (line 222 in branch dhd2016): 

```
# (optional) remove punctuation, special characters and space-chains
#text = re.sub("[,;\.:!?¿\(\)—-]", " ", text)
text = re.sub("[\t\r\n\v\f]", " ", text)
text = re.sub("[ ]{1,9}", " ", text)
```

Punctuation, special characters and sequences of spaces are each on a separate line and may be commented out as needed. According to your suggestion, the default is to leave punctuation in the texts.

**Comment by christofs** [comment]
Please test the latest version!

**Comment by morethanbooks** [comment]
Perfect. Thanks!
