### ISSUE TITLE
Some values in variables

### ISSUE THREAD

**Issue by morethanbooks** [cligs/tmw#11]
In the script tmw_config you have to define many times the number of topics. That should be treated as variable.
I think the targets should be also saved in a list that you can always use in the different steps.

**Comment by christofs** [comment]
This variable is now called `numOfTopics` and defined once in `call_mallet_model`. Later on, that value is simply used whenever the total number of topics is needed. The reference is still there in the individual functions' parameters to make clear where the information comes from and to allow overriding this, for example for testing purposes.

**Comment by christofs** [comment]
Testing seems to confirm everything is alright.

**Comment by christofs** [comment]
I have not added the targets as another variable to define once for all functions. It may vary with what you are interested. Also, what actually makes sense varies a bit between functions. Let's wait a little bit before we consider making this a once-for-all variable.
