### ISSUE TITLE
Defining paths at the beginning of tmw_config

### ISSUE THREAD

**Issue by morethanbooks** [cligs/tmw#12]
At the beginning of the tmw_config you have to define the path to wdir. This is very easy to see. I think the other paths (to mallet, to treetagger and so on) should be also define at the beginning of the script and not every time in the different steps.

**Comment by christofs** [comment]
This is a good idea. Let's do this, at first, by simply moving the definition at the top but keeping the parameter in the list of parameters, so that it remains clear where the information comes from.
